CREATE DATABASE IF NOT EXISTS SHOP_SHEN DEFAULT CHARSET UTF8 COLLATE UTF8_GENERAL_CI ;

USE SHOP_SHEN;

DROP TABLE IF EXISTS USER;

CREATE TABLE USER(
USER_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '用户ID',
USER_NAME  VARCHAR (50) NOT NULL UNIQUE COMMENT '登陆用户名',
PASSWORD  VARCHAR (50) NOT NULL COMMENT '登陆密码',
STATUS   TINYINT(1)   NOT NULL DEFAULT '1' COMMENT '状态 0未激活  1：激活；2：禁用',
PHONE  VARCHAR(20)  UNIQUE COMMENT '手机号码',
SEX TINYINT(1)  NOT NULL DEFAULT '1' COMMENT '性别 0为女  1为男',
ADDERSS VARCHAR(255)  COMMENT '地址',
REALNAME VARCHAR(50) NOT NULL COMMENT '真实姓名',
EMAIL VARCHAR(20)  UNIQUE COMMENT '邮箱',
PIC_NAME VARCHAR(255) COMMENT '头像',
CREATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '创建人ID',
CREATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
UPDATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '修改人ID',
UPDATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '修改时间',
PRIMARY KEY(USER_ID),
KEY IDX_USER_STATUS(STATUS),
KEY IDX_USER_SEX(SEX)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='登录用户表';


DROP TABLE IF EXISTS ADMINS;

CREATE TABLE ADMINS(
ADMINS_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '管理员ID',
ADMINS_NAME  VARCHAR (50) NOTI NULL UNIQUE COMMENT '管理员用户名',
ADMINS_PASSWORD VARCHAR(50) NOT NULL COMMENT '管理员密码',
STATUS   TINYINT(1)   NOT NULL DEFAULT '1' COMMENT '状态 0未激活  1：激活；2：禁用',
PRIMARY KEY(ADMINS_ID),
KEY IDX_ADMINS_STATUS(STATUS)
)ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT='管理员表';

DROP TABLE EXISTS ORDERS;


CREATE TABLE ORDERS(
ORDERS_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '订单ID',
USER_ID BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
TOTAL DOUBLE (9, 2) UNSIGNED NOT NULL COMMENT '订单价格',
STATUS TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '状态 1.未付款2.已付款,为发货3.已发货4.确认收货5.取消订单',
CODE VARCHAR(8) NOT NULL COMMENT '邮政编码',
PHONE VARCHAR(11) NOT NULL COMMENT '电话',
CREATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '创建人ID',
CREATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '创建时间',
UPDATE_BY BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '修改人ID',
UPDATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '修改时间',
PRIMARY KEY (ORDERS_ID),
KEY IDX_ORDERS_STATUS(STATUS)
)ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT = '订单表' ;


DROP TABLE IF EXISTS ORDER_INFO;

CREATE TABLE ORDER_INFO(
ORDER_INFO_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '订单详情ID',
USER_ID BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
ORDERS_ID BIGINT UNSIGNED  COMMENT '订单ID',
OINAME VARCHAR(20) NOT NULL COMMENT '收件人名字',
PIC DOUBLE (9, 2) UNSIGNED NOT NULL COMMENT '金额',
GOODS_ID BIGINT UNSIGNED NOT NULL COMMENT '商品ID',
NUM  TINYINT(5) UNSIGNED NOT NULL COMMENT '购买数量',
PRIMARY KEY (ORDER_INFO_ID),
KEY IDX_USER_ID(USER_ID),
KEY IDX_ORDERS_ID(ORDERS_ID),
KEY IDX_GOODS_ID(GOODS_ID)
)ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='订单详情';


DROP TABLE IF EXISTS CAREGORY;

CREATE TABLE CAREGORY(
CAREGORY_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '商品ID',
INFOR VARCHAR(255) COMMENT '商品描述',
CNAME VARCHAR(32) COMMENT '分类名称',
IMG VARCHAR(255) COMMENT '商品分类图片',
CID BIGINT UNSIGNED NOT NULL COMMENT'父类ID号',
PRIMARY KEY (CAREGORY_ID),
KEY IDX_CAREGORY_CID(CID),
KEY IDX_CAREGORY_CNAME(CNAME)
)ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='商品分类表';


DROP TABLE IF EXISTS GOODS;

CREATE TABLE GOODS(
GOODS_ID  BIGINT UNSIGNED AUTO_INCREMENT COMMENT '商品ID',
GNAME VARCHAR(255) NOT NULL COMMENT'商品名称',
CAREGORY_ID  BIGINT UNSIGNED NOT NULL COMMENT '类别',
PRICE DOUBLE (9, 2) UNSIGNED NOT NULL COMMENT '商品单价',
OLDPRICE DOUBLE (9, 2) UNSIGNED NOT NULL COMMENT '商品原价',
STORE BIGINT  UNSIGNED NOT NULL COMMENT '商品存储量',
STATUS TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '商品状态 1.新添加 2.在售 3.下架',
DESCR  VARCHAR(255) NOT NULL COMMENT '商品简介',
NUM BIGINT COMMENT '购买数量',
CLICKNUM BIGINT COMMENT '点击次数',
COMPANG VARCHAR(100) COMMENT '生产厂家',
PICNAME VARCHAR(255)  COMMENT '图片名称',
PRIMARY KEY (GOODS_ID),
KEY IDX_GOODS_GNAME(GNAME),
KEY IDX_GOODS_STATUS(STATUS)
)ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='商品详情表';


DROP TABLE IF EXISTS IMG;

CREATE TABLE IMG(
IMG_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '图片ID',
GOODS_ID  BIGINT UNSIGNED COMMENT '商品ID',
PICNAME VARCHAR(255)  COMMENT '图片名称',
PRIMARY KEY (IMG_ID),
KEY IDX_IMG_GOODS_ID(GOODS_ID)
)ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='图片表';



DROP TABLE IF EXISTS COMMMENT;

CREATE TABLE COMMMENT(
 COMMMENT_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '评价ID',
 GOODS_ID  BIGINT UNSIGNED COMMENT '商品ID',
 USER_ID BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
 CONENT VARCHAR(255) COMMENT '评价内容',
 level TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '评价等级  1星    2星    3星   4星   5星 ',
 CREATE_BY   BIGINT UNSIGNED NOT NULL DEFAULT '1000' COMMENT '创建人ID',
 CREATE_DATE DATETIME NOT NULL DEFAULT NOW() COMMENT '评价时间',
 PRIMARY KEY (COMMMENT_ID),
 KEY IDX_GOODS_ID(GOODS_ID),
 KEY IDX_USER_ID(USER_ID)
)ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='评价表';



DROP TABLE IF EXISTS NORMS;

CREATE TABLE NORMS(
NOTMS_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '规格ID',
COLOR TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '颜色 1   2    3   4   5   6   7',
SIZE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '大小 1   2    3   4   5   6   7',
COPYS TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '版本 1   2    3   4   5   6   7',
EQUIV TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '配置 1   2    3   4   5   6   7',
SERVICE TINYINT UNSIGNED NOT NULL DEFAULT '1' COMMENT '延保服务 1   2    3   4   5',
 PRIMARY KEY (NOTMS_ID)
)ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='商品规格表';


DROP TABLE IF EXISTS PIC;

CREATE TABLE PIC(
PIC_ID BIGINT UNSIGNED AUTO_INCREMENT COMMENT '图片轮播ID',
PIC_NAME VARCHAR(255) NOT NULL COMMENT '图片名称',
PIC_STATUS TINYINT NOT NULL  DEFAULT '2' COMMENT '1.显示 2 不显示 ',
 PRIMARY KEY (PIC_ID),
 KEY IDX_PIC_NAME(PIC_NAME)
)ENGINE = INNODB  CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='轮播表';



DROP TABLE IF EXISTS NOTIFY_LOG;

CREATE TABLE NOTIFY_LOG (
  SN BIGINT AUTO_INCREMENT COMMENT '日志ID',
  CMD_TYPE VARCHAR (100) NOT NULL COMMENT '操作类型',
  TABLE_NAME VARCHAR (100) NOT NULL COMMENT '表名',
  PK_VALUES VARCHAR (100) NOT NULL COMMENT '主键值',
  WHERE_CONDITION VARCHAR (100) NOT NULL COMMENT '条件',
  PRIMARY KEY(SN)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 AUTO_INCREMENT = 1000 COMMENT='日志表';


DROP TABLE IF EXISTS `ORDER_SEQ` ;

CREATE TABLE ORDER_SEQ (
  TIMESTR VARCHAR (20) NOT NULL,
  ORDER_SN INT NOT NULL
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COMMENT = '生成订单编号' ;


